<?php

/**
 * @file
 * Date Recur Subfield hooks.
 */

/**
 * Implements hook_field_widget_info_alter().
 */
function date_recur_subfield_field_field_widget_info_alter(array &$info) {
  // Duplicate date_recur widgets for date_recur_sub field.
  foreach ($info as $widgetId => $widgetInfo) {
    if (in_array('date_recur', $widgetInfo['field_types'])) {
      $info[$widgetId]['field_types'][] = 'date_recur_sub';
    }
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function date_recur_subfield_field_field_formatter_info_alter(array &$info) {
  // Duplicate date_recur formatters for date_recur_sub field.
  foreach ($info as $formatterId => $formatterInfo) {
    if (in_array('date_recur', $formatterInfo['field_types'])) {
      $info[$formatterId]['field_types'][] = 'date_recur_sub';
    }
  }
}
