# Schema for the views style plugins.

views.style.leaflet_map:
  type: views_style
  label: 'Leaflet map'
  mapping:
    data_source:
      type: string
      label: 'Data source'
    entity_source:
      type: string
      label: 'Entity source'
    entity_source_submit:
      type: string
      label: 'Submit label for entity source'
    name_field:
      type: string
      label: 'Name field'
    description_field:
      type: string
      label: 'Description field'
    view_mode:
      type: string
      label: 'View mode'
    leaflet_map:
      type: string
      label: 'Leaflet map'
    height:
      type: string
      label: 'Map height'
    height_unit:
      type: string
      label: 'Height unit'
    hide_empty_map:
      type: boolean
      label: 'Hide empty map'
    disable_wheel:
      type: boolean
      label: 'Disable wheel'
    fullscreen_control:
      type: boolean
      label: 'Fulllscreen control'
    gesture_handling:
      type: boolean
      label: 'Gesture handling'
    reset_map:
      type: mapping
      label: 'Reset map'
      mapping:
        control:
          type: boolean
          label: 'Control'
        position:
          type: string
          label: 'Position'
    map_position:
      type: mapping
      label: 'Map position'
      mapping:
        force:
          type: boolean
          label: 'Force map center & zoom'
        center:
          type: mapping
          label: 'Centre'
          mapping:
            lat:
              type: integer
              label: 'Lattitude'
            lon:
              type: integer
              label: 'Longitude'
        zoom:
          type: integer
          label: 'Zoom'
        minZoom:
          type: integer
          label: 'Minimum zoom'
        maxZoom:
          type: integer
          label: 'Maximum zoom'
        zoomFiner:
          type: integer
          label: 'Zoomfiner'
    weight:
      type: string
      label: 'Weight'
    icon:
      type: mapping
      label: 'Map icon'
      mapping:
        iconType:
          type: string
          label: 'Icon type'
        iconUrl:
          type: string
          label: 'Icon URL'
        shadowUrl:
          type: string
          label: 'Shadow URL'
        className:
          type: string
          label: 'Icon class'
        iconSize:
          type: mapping
          label: 'Icon size'
          mapping:
            x:
              type: string
              label: 'Width'
            y:
              type: string
              label: 'Height'
        iconAnchor:
          type: mapping
          label: 'Icon anchor'
          mapping:
            x:
              type: string
              label: 'Width'
            y:
              type: string
              label: 'Height'
        shadowSize:
          type: mapping
          label: 'Shadow anchor'
          mapping:
            x:
              type: string
              label: 'Width'
            y:
              type: string
              label: 'Height'
        shadowAnchor:
          type: mapping
          label: 'Shadow anchor'
          mapping:
            x:
              type: string
              label: 'Width'
            y:
              type: string
              label: 'Height'
        popupAnchor:
          type: mapping
          label: 'Popup anchor'
          mapping:
            x:
              type: string
              label: 'Width'
            y:
              type: string
              label: 'Height'
        html:
          type: string
          label: 'HTML'
        html_class:
          type: string
          label: 'HTML class'
        circle_marker_options:
          type: string
          label: 'Circle marker options'
    leaflet_markercluster:
      type: mapping
      label: 'Leaflet Markercluster'
      mapping:
        control:
          type: boolean
          label: 'Control'
        options:
          type: text
          label: 'Options'
    path:
      type: string
      label: 'Path'
    geocoder:
      type: mapping
      label: 'Geocoder'
      mapping:
        control:
          type: boolean
          label: 'Control'
        settings:
          type: mapping
          label: 'Geocoder'
          mapping:
            position:
              type: string
              label: 'Path'
            input_size:
              type: integer
              label: 'Input size'
            providers:
              type: sequence
              label: 'Providers'
              sequence:
                type: mapping
                mapping:
                  weight:
                    type: string
                    label: 'Weight'
                  checked:
                    type: integer
                    label: 'Checked'
            min_terms:
              type: integer
              label: 'Minimum terms'
            delay:
              type: integer
              label: 'Delay'
            zoom:
              type: integer
              label: 'Zoom'
            popup:
              type: boolean
              label: 'Popup'
            options:
              type: string
              label: 'Options'
