<?php

/**
 * @file
 * Contains le_afeefa_api_service.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function le_afeefa_api_service_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the le_remote_api_services module.
    case 'help.page.le_afeefa_api_service':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import and sync afeefa.de') . '</p>';
      return $output;

    default:
  }
}
