<?php

/**
 * @file
 * Contains avatar_field_formatter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avatar_field_formatter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the avatar_field_formatter module.
    case 'help.page.avatar_field_formatter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('An image field formatter, if the image does not exist, display an avatar letter instead.') . '</p>';
      return $output;

    default:
  }
}
