<?php
function le_webbuilder_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if ($form_id == 'node_webbuilder_page_form') {
    $webbuilder_id = \Drupal::request()->query->get('webbuilder');

    if ($webbuilder_id) {
      $webbuilder = \Drupal::entityManager()->getStorage('node')->load($webbuilder_id);
      $akteur_id = $webbuilder->field_akteur[0]->target_id;
      $form['og_audience']['#attributes']['class'][] = 'hidden';
      $form['og_audience']['widget']['#default_value'] = $akteur_id;
      $form['field_webbuilder']['#attributes']['class'][] = 'hidden';
      $form['field_webbuilder']['widget']['#default_value'] = $webbuilder_id;
    }
  }

  if ($form_id === 'node_webbuilder_edit_form') {
    $node_id = $form_state->getFormObject()->getEntity()->id();

    $form['group_pages']['field_page_tree'] = [
      '#type' => 'inline_template',
      '#template' => '<label class="form-item__label">Seitenbaum</label> {{ drupal_view(\'webbuilder_pages\', \'form_page_tree\', ' . $node_id . ')}}',
      '#weight' => 100,
    ];
    $dest = \Drupal::destination()->getAsArray()['destination'];
    $form['group_pages']['field_add_page'] = [
      '#type' => 'markup',
      '#markup' => '<a class="button button--default" href="/node/add/webbuilder_page?webbuilder=' . $node_id . '&destination=' . urlencode($dest) . '">+ ' . t('Add page') . '</a>',
      '#weight' => 101,
    ];
  }

  if (in_array($form_id, ['media_unsplash_image_add_form', 'media_unsplash_image_edit_form'])) {
    $form['search'] = [
      '#type' => 'search',
      '#title' => t('Search images'),
      '#placeholder' => t('Enter search terms'),
      '#attributes' => [
        'data-results-target' => '#edit-field-unsplash-search-results',
        'data-preview-target' => '#edit-field-image-preview',
        'data-url-target' => '#edit-field-media-remote-image-0-uri',
        'data-alt-target' => '#edit-field-media-remote-image-0-alt',
        'data-title-target' => '#edit-name-0-value',
        'data-attribution-target' => '#edit-field-attribution-0-value',
        'data-api-url' => '/webbuilder/unsplash-api-proxy',
        'oninput' => 'handleUnsplashSearchInput(this)',
        'autocomplete' => 'off',
      ],
      '#weight' => -100,
    ];
    $form['search_results'] = [
      '#type' => 'markup',
      '#markup' => '<div class="unsplash-results" id="edit-field-unsplash-search-results"></div>',
      '#weight' => -99,
    ];
    $form['image_preview'] = [
      '#type' => 'markup',
      '#markup' => '<figure class="unsplash-preview" id="edit-field-image-preview"></figure>',
      '#weight' => -98,
    ];

    // hide attribution field, so user cannot enter values
    // $form['field_attribution']['#attributes']['class'][] = 'hidden';

    $form['#attached']['library'][] = 'le_webbuilder/unsplash_media_form';
  }
}
