<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\og\Og;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Called on UI-change event of $field_{le_entity_type}_kategorie_typ.
 * Returns a renderable array that replaces the wrapper-container.
 */
function ajax_field_kategorie_typ_callback(&$form, FormStateInterface $form_state) {
  return isset($form['field_le_akteur_kategorie_subtyp']) ? $form['field_le_akteur_kategorie_subtyp'] : $form['field_le_event_kategorie_subtyp'];
}

function le_core_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() === 'le_view_user_has_akteure') {
    // @todo Override link to Akteur by showing full Akteur name
  }

  if ($view->id() === 'le_view_akteure' || $view->id() === 'le_view_events') {
    // Attach custom, JS-based categories selector
    $view->element['#attached']['library'][] = 'le_core/categories-select';
  }
}

/**
 * Implements hook_menu_local_tasks_alter
 */
function le_core_menu_local_tasks_alter(&$data, $route_name)
{
  if ($route_name === 'entity.node.canonical' || $route_name === 'view.le_akteur_has_events.page_1' || $route_name === 'entity.node.edit_form') {
    // Context: node

    $tabs = $data['tabs'][0]; 

    if (isset($data['tabs'][0]) && isset($data['tabs'][0]['entity.node.canonical'])) {
      // Change first tab title from "Ansicht" to "Beschreibung"
      $local_task_main_view = &$data['tabs'][0]['entity.node.canonical'];
      $local_task_main_view['#link']['title'] = 'Beschreibung';
    }

    /** @var \Drupal\node\Entity\Node $node */
    $node = \Drupal::routeMatch()->getParameter('node');

    if ($node && gettype($node) !== 'string' && $node->bundle() !== 'le_akteur') {
      // Only show "Akteur-has-events" view link on akteur nodes
      $data['tabs'][0]['view.le_akteur_has_events.page_1']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function le_core_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id = NULL)
{

  if (in_array($form_id, ['node_le_akteur_form','node_le_akteur_edit_form'])) {
    set_kategorie_form_fields($form, $form_state, 'akteur');
  }

  if (in_array($form_id, ['node_le_event_form','node_le_event_edit_form'])) {
    set_kategorie_form_fields($form, $form_state, 'event');

    // Get groups ("memberships") of active user; if none, redirect to "/events"
    $user_id = \Drupal::currentUser()->id();
    $full_user = \Drupal\user\Entity\User::load($user_id);
    $user_is_admin = $full_user->hasRole('administrator') || $user_id == 1;
    
    $membership_manager = \Drupal::service('og.membership_manager');
    $user_memberships = $membership_manager->getMemberships($user_id);

    if (!count($user_memberships) && !$user_is_admin) {
        \Drupal::messenger()->addError(t('Du musst mind. einem Akteur zugeordnet sein, um Events erstellen zu können'));
        $response = new RedirectResponse('/events');
        $response->send();
        return;
    }

    // As long as recurrencies widget UI is not completed: Hide fields "mode" and "timezone"
    $field_occurrences_widget = &$form['field_le_event_occurrences']['widget'];

    foreach($field_occurrences_widget as $key => $field_occurrence) {
        if (!is_numeric($key)) continue;
        $field_occurrences_widget[$key]['mode']['#attributes']['class'][] = 'hidden'; // #access = false would break JS behaviour :/
        $field_occurrences_widget[$key]['time_zone']['#access'] = false;
        $field_occurrences_widget[$key]['blakeks'] = [
            '#type' => 'checkbox',
            '#title' => 'blakeks',//$this->t('Whether to enable occurrences button'),
            '#default_value' => 1,
            '#description' => 'efw',
            '#weight' => -1,
          ];
    }

    $form['#attached']['library'][] = 'le_core/event-form';

   /* $form['#attached'] = array(
      'library' => array('openlayers/drupal-addlayer'),
      'drupalSettings' => array(),
    );*/


    // @todo Hide several fields when user is not drupal admin

    // @todo Turn autocomplete into native select

    // $form['og_audience']['widget'][0]['target_id']['#type'] = 'select';
    // $form['og_audience']['widget'][0]['target_id']['#options'] = [
    //   'a' => 'A',
    //   'b' => 'B'
    // ];

    if (in_array($form_id, ['node_le_event_form']) && count($user_memberships) >= 1) {
        // Add event form: Set first akteur as default in select-list
        $default_akteur = $user_memberships[key($user_memberships)]->entity_id->value;
        $default_akteur = \Drupal\node\Entity\Node::load((int) $default_akteur);

        if ($default_akteur) {
          // @todo may be empty as memberships become not deleted on node.le_akteur delete :(
          $form['og_audience']['widget'][0]['target_id']['#default_value'] = $default_akteur;
        }
    }
  }
}

/**
 * Dynamically set the select options of $field_{le_entity_type}_kategorie_typ & - _subtyp based on user input.
 * ("Select one main category; select multiple second categories which are children of that main category")
 */
function set_kategorie_form_fields(&$form, FormStateInterface $form_state, $le_entity_type)
{

  $kategorie_typ_field = "field_le_${le_entity_type}_kategorie_typ";
  $kategorie_subtyp_field = "field_le_${le_entity_type}_kategorie_subtyp";

  // Get main category value based on context (default render || ajax request)
  $full_entity = $form_state->getFormObject()->getEntity();

  $field_kategorie_typ_default_value = $full_entity->get($kategorie_typ_field)->getValue();
  $field_kategorie_typ_ajax_value = $form_state->getValue($kategorie_typ_field);

  $field_kategorie_typ_value = null;

  if (isset($field_kategorie_typ_default_value[0])) {
    $field_kategorie_typ_value = (int) $field_kategorie_typ_default_value[0]['target_id'];
  }

  if (isset($field_kategorie_typ_ajax_value[0])) {
    $field_kategorie_typ_value = (int) $field_kategorie_typ_ajax_value[0]['target_id'];
  }

  $kategorien = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('le_kategorie_typ');

  // Set main category select options
  $first_option_kategorien = [
    '_none' => '- Nicht ausgewählt -'
  ];

  foreach ($kategorien as $kategorie) {
    if ((int) $kategorie->parents[0] === 0) {
      $first_option_kategorien[$kategorie->tid] = $kategorie->name;
    }
  }

  $form[$kategorie_typ_field]['widget']['#options'] = $first_option_kategorien;
  $form[$kategorie_typ_field]['widget']['#ajax'] = array(
    'callback' => 'ajax_field_kategorie_typ_callback',
    'wrapper' => 'field-kategorie-subtyp-wrapper',
    'method' => 'replace',
    // 'effect' => 'fade',
  );

  // Set sub-category select options based on $field_kategorie_typ_value
  // @todo Eventually we wanna hide/disable this field completely as long as $field_kategorie_typ_value === NULL
  $second_option_kategorien = [
    '_none' => $field_kategorie_typ_value ? '- Nicht ausgewählt -' : '- Wähle zunächst Hauptkategorie -'
  ];

  if ($field_kategorie_typ_value) {
    foreach ($kategorien as $kategorie) {
      if ((int) $kategorie->parents[0] === $field_kategorie_typ_value) {
        $second_option_kategorien[$kategorie->tid] = $kategorie->name;
      }
    }
  }

  $form[$kategorie_subtyp_field]['widget']['#options'] = $second_option_kategorien;

  // Set wrapper in which output of ajax_field_kategorie_typ_callback() will be rendered into.
  $form[$kategorie_subtyp_field]['widget']['#prefix'] = '<div id="field-kategorie-subtyp-wrapper">';
  $form[$kategorie_subtyp_field]['widget']['#suffix'] = '</div>';
}
