remove_http_headers.settings:
  type: config_object
  label: 'The module configuration.'
  mapping:
    headers_to_remove:
      type: sequence
      label: 'The HTTP headers that should be removed from responses.'
      sequence:
        type: string
    dependencies:
      type: mapping
      label: 'Dependency information.'
      mapping:
        enforced:
          type: mapping
          label: 'Enforced dependencies.'
          mapping:
            module:
              type: sequence
              label: 'Module dependencies.'
              sequence:
                type: string
